POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.myntra.com/watches/michael-kors/michael-kors-women-off-white-chronograph-watch-mk6266/12035280/buy"
}